Добавляет hw04
Oleg-Khakhuda/nodejs-homework-rest-api pull request #3
Opened 2021-12-31 09:06 UTC by Oleg-Khakhuda

2022-01-04 22:52 UTC, KirillKulakow commented on middlewares/rate-limit.js
> +import rateLimit from 'express-rate-limit'
не помню чтобы это было в ТЗ по домашнему заданию

2022-01-04 23:04 UTC, KirillKulakow commented on controllers/users/index.js
> +import repositoryContacts from '../../repository/contacts'
что это за файл?
не видел данного задания в ТЗ по домашнему заданию

2022-01-04 23:06 UTC, KirillKulakow commented on repository/contacts.js
> +  const total = await Contact.find({owner: userId}).countDocuments()
почему не написать await Contact.countDocuments({owner: userId})

2022-01-04 23:07 UTC, KirillKulakow commented on repository/contacts.js
> +const getStatisticsContacts = async (id) => {
это есть в ТЗ?

2022-01-04 23:07 UTC, KirillKulakow commented on routes/api/users/index.js
> +
тот же вопрос

2022-01-04 23:08 UTC, KirillKulakow commented on routes/api/auth/index.js
> +router.post('/logout', guard, logout)
где роут /current?

2022-01-04 23:08 UTC, KirillKulakow requested changes
Need fix

2022-01-08 09:57 UTC, Oleg-Khakhuda commented on middlewares/rate-limit.js
> +import rateLimit from 'express-rate-limit'
Мы это делали на уроке, преподаватель Юрий Кучма сказал что можно добавить в проект

2022-01-08 09:57 UTC, Oleg-Khakhuda commented on controllers/users/index.js
> +import repositoryContacts from '../../repository/contacts'
Мы это делали на уроке, преподаватель Юрий Кучма сказал что можно добавить в проект

2022-01-08 09:58 UTC, Oleg-Khakhuda commented on repository/contacts.js
> +const getStatisticsContacts = async (id) => {
Мы это делали на уроке, преподаватель Юрий Кучма сказал что можно добавить в проект

2022-01-08 09:58 UTC, Oleg-Khakhuda commented on routes/api/users/index.js
> +
Мы это делали на уроке, преподаватель Юрий Кучма сказал что можно добавить в проект

2022-01-10 21:23 UTC, KirillKulakow commented on controllers/auth/index.js
> +  console.log(token);
зачем эти две строки?

2022-01-10 21:24 UTC, KirillKulakow reviewed
Need fix

2022-01-11 20:14 UTC, KirillKulakow approved these changes

2022-01-13 20:44 UTC, merged